version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
    groups:
      drift:
        patterns: ["drift", "drift_dev"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
